"""lifecycle

Revision ID: 20260903_0005
Revises: 20260902_0004
Create Date: 2026-09-03 09:56:42.601971
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260903_0005"
down_revision: str | None = "20260902_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name_zh", sa.String(length=200), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dataset_categories_code"), "dataset_categories", ["code"], unique=True)
    op.create_table(
        "datasets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active','archived')", name="ck_datasets_status"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_datasets_owner_id"), "datasets", ["owner_id"], unique=False)
    op.create_index(op.f("ix_datasets_project_id"), "datasets", ["project_id"], unique=False)
    op.create_index(
        "ix_datasets_project_status", "datasets", ["project_id", "status"], unique=False
    )
    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("train_ratio", sa.Integer(), nullable=False),
        sa.Column("val_ratio", sa.Integer(), nullable=False),
        sa.Column("test_ratio", sa.Integer(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("annotation_count", sa.Integer(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft','frozen','training','published','archived')",
            name="ck_dataset_versions_status",
        ),
        sa.CheckConstraint("revision > 0", name="ck_dataset_version_revision"),
        sa.CheckConstraint(
            "sample_count >= 0 AND annotation_count >= 0 AND byte_size >= 0",
            name="ck_dataset_version_counters",
        ),
        sa.CheckConstraint(
            "train_ratio + val_ratio + test_ratio = 100", name="ck_dataset_split_sum"
        ),
        sa.CheckConstraint(
            "train_ratio BETWEEN 0 AND 100 AND val_ratio BETWEEN 0 AND 100 "
            "AND test_ratio BETWEEN 0 AND 100",
            name="ck_dataset_split_ranges",
        ),
        sa.CheckConstraint("version_number > 0", name="ck_dataset_versions_number"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "version_number"),
    )
    op.create_index(
        op.f("ix_dataset_versions_dataset_id"), "dataset_versions", ["dataset_id"], unique=False
    )
    op.create_index(
        "ix_dataset_versions_dataset_status",
        "dataset_versions",
        ["dataset_id", "status"],
        unique=False,
    )
    op.create_table(
        "dataset_samples",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=20), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("source_video_id", sa.Uuid(), nullable=True),
        sa.Column("frame_index", sa.Integer(), nullable=True),
        sa.Column("timestamp_ms", sa.BigInteger(), nullable=True),
        sa.Column("split", sa.String(length=20), nullable=False),
        sa.Column("review_status", sa.String(length=30), nullable=False),
        sa.Column("duplicate_group", sa.String(length=64), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("media_type IN ('image','video')", name="ck_dataset_sample_media_type"),
        sa.CheckConstraint(
            "review_status IN ('unreviewed','approved','changes_requested')",
            name="ck_dataset_sample_review_status",
        ),
        sa.CheckConstraint(
            "split IN ('unassigned','train','val','test')", name="ck_dataset_sample_split"
        ),
        sa.CheckConstraint(
            "(frame_index IS NULL OR frame_index >= 0) "
            "AND (timestamp_ms IS NULL OR timestamp_ms >= 0)",
            name="ck_dataset_sample_frame_position",
        ),
        sa.CheckConstraint(
            "(width IS NULL OR width > 0) AND (height IS NULL OR height > 0)",
            name="ck_dataset_sample_dimensions",
        ),
        sa.CheckConstraint("byte_size > 0", name="ck_dataset_sample_byte_size"),
        sa.CheckConstraint("revision > 0", name="ck_dataset_sample_revision"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["source_video_id"], ["dataset_samples.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["version_id"], ["dataset_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(op.f("ix_dataset_samples_sha256"), "dataset_samples", ["sha256"], unique=False)
    op.create_index(
        "ix_dataset_samples_version_hash", "dataset_samples", ["version_id", "sha256"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_samples_version_id"), "dataset_samples", ["version_id"], unique=False
    )
    op.create_index(
        "ix_dataset_samples_version_split", "dataset_samples", ["version_id", "split"], unique=False
    )
    op.create_table(
        "lifecycle_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=True),
        sa.Column("model_version_id", sa.Uuid(), nullable=True),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("progress_detail", sa.String(length=500), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("claimed_by", sa.String(length=100), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("log_storage_key", sa.String(length=500), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_detail", sa.String(length=1000), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('extract','validate','export','train','evaluate')",
            name="ck_lifecycle_job_kind",
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','cancelling','cancelled','succeeded','failed')",
            name="ck_lifecycle_job_status",
        ),
        sa.CheckConstraint(
            "attempt >= 1 AND max_attempts >= attempt", name="ck_lifecycle_attempts"
        ),
        sa.CheckConstraint("progress BETWEEN 0 AND 100", name="ck_lifecycle_job_progress"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(["version_id"], ["dataset_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lifecycle_jobs_kind"), "lifecycle_jobs", ["kind"], unique=False)
    op.create_index(
        op.f("ix_lifecycle_jobs_owner_id"), "lifecycle_jobs", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_lifecycle_jobs_project_id"), "lifecycle_jobs", ["project_id"], unique=False
    )
    op.create_index(
        "ix_lifecycle_jobs_queue", "lifecycle_jobs", ["status", "queued_at"], unique=False
    )
    op.create_index(op.f("ix_lifecycle_jobs_status"), "lifecycle_jobs", ["status"], unique=False)
    op.create_table(
        "dataset_changes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("sample_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("before_state", sa.JSON(), nullable=True),
        sa.Column("after_state", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["sample_id"], ["dataset_samples.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["dataset_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_dataset_changes_sample_created",
        "dataset_changes",
        ["sample_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dataset_changes_version_id"), "dataset_changes", ["version_id"], unique=False
    )
    op.create_table(
        "lifecycle_artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("byte_size >= 0", name="ck_lifecycle_artifact_byte_size"),
        sa.ForeignKeyConstraint(["job_id"], ["lifecycle_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_lifecycle_artifacts_job_id"), "lifecycle_artifacts", ["job_id"], unique=False
    )
    op.create_table(
        "quality_findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("sample_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("suggestion", sa.String(length=1000), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "severity IN ('info','warning','error')", name="ck_quality_finding_severity"
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["sample_id"], ["dataset_samples.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["version_id"], ["dataset_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quality_findings_version_id"), "quality_findings", ["version_id"], unique=False
    )
    op.create_index(
        "ix_quality_version_code",
        "quality_findings",
        ["version_id", "code", "resolved"],
        unique=False,
    )
    op.create_table(
        "sample_annotations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sample_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("cx", sa.Float(), nullable=False),
        sa.Column("cy", sa.Float(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "cx - width / 2 >= 0 AND cx + width / 2 <= 1 "
            "AND cy - height / 2 >= 0 AND cy + height / 2 <= 1",
            name="ck_annotation_within_image",
        ),
        sa.CheckConstraint("cx BETWEEN 0 AND 1", name="ck_annotation_cx"),
        sa.CheckConstraint("cy BETWEEN 0 AND 1", name="ck_annotation_cy"),
        sa.CheckConstraint("height > 0 AND height <= 1", name="ck_annotation_height"),
        sa.CheckConstraint("width > 0 AND width <= 1", name="ck_annotation_width"),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["dataset_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["sample_id"], ["dataset_samples.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_annotations_sample", "sample_annotations", ["sample_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_sample_annotations_sample_id"), "sample_annotations", ["sample_id"], unique=False
    )
    op.create_table(
        "training_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=False),
        sa.Column("train_loss", sa.Float(), nullable=True),
        sa.Column("val_loss", sa.Float(), nullable=True),
        sa.Column("map50", sa.Float(), nullable=True),
        sa.Column("map50_95", sa.Float(), nullable=True),
        sa.Column("precision", sa.Float(), nullable=True),
        sa.Column("recall", sa.Float(), nullable=True),
        sa.Column("f1", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(map50 IS NULL OR map50 BETWEEN 0 AND 1) "
            "AND (map50_95 IS NULL OR map50_95 BETWEEN 0 AND 1) "
            "AND (precision IS NULL OR precision BETWEEN 0 AND 1) "
            "AND (recall IS NULL OR recall BETWEEN 0 AND 1) "
            "AND (f1 IS NULL OR f1 BETWEEN 0 AND 1)",
            name="ck_training_metric_scores",
        ),
        sa.CheckConstraint("epoch >= 0", name="ck_training_metric_epoch"),
        sa.ForeignKeyConstraint(["job_id"], ["lifecycle_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "epoch"),
    )
    op.create_index(
        op.f("ix_training_metrics_job_id"), "training_metrics", ["job_id"], unique=False
    )
    op.create_table(
        "managed_model_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("scene", sa.String(length=30), nullable=False),
        sa.Column("size_variant", sa.String(length=1), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("training_job_id", sa.Uuid(), nullable=True),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=True),
        sa.Column("weight_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("model_card", sa.Text(), nullable=False),
        sa.Column("class_map_json", sa.JSON(), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("scene IN ('pipeline','ppe')", name="ck_managed_model_scene"),
        sa.CheckConstraint("size_variant IN ('n','s','m','l','x')", name="ck_model_size_variant"),
        sa.CheckConstraint(
            "status IN ('draft','evaluating','published','archived')",
            name="ck_managed_model_status",
        ),
        sa.CheckConstraint("version_number > 0", name="ck_managed_model_version_number"),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_versions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["training_job_id"], ["lifecycle_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["weight_artifact_id"],
            ["lifecycle_artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "version_number"),
    )
    op.create_index(
        op.f("ix_managed_model_versions_code"), "managed_model_versions", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_managed_model_versions_status"), "managed_model_versions", ["status"], unique=False
    )
    op.create_index(
        "ix_managed_models_status", "managed_model_versions", ["status", "scene"], unique=False
    )
    op.create_table(
        "model_deployments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("scene", sa.String(length=30), nullable=False),
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("previous_model_version_id", sa.Uuid(), nullable=True),
        sa.Column("rollout_percent", sa.Integer(), nullable=False),
        sa.Column("deployed_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rollout_percent BETWEEN 0 AND 100", name="ck_deployment_rollout"),
        sa.ForeignKeyConstraint(
            ["deployed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["managed_model_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_model_version_id"],
            ["managed_model_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "scene"),
    )
    op.create_index(
        op.f("ix_model_deployments_project_id"), "model_deployments", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_model_deployments_project_id"), table_name="model_deployments")
    op.drop_table("model_deployments")
    op.drop_index("ix_managed_models_status", table_name="managed_model_versions")
    op.drop_index(op.f("ix_managed_model_versions_status"), table_name="managed_model_versions")
    op.drop_index(op.f("ix_managed_model_versions_code"), table_name="managed_model_versions")
    op.drop_table("managed_model_versions")
    op.drop_index(op.f("ix_training_metrics_job_id"), table_name="training_metrics")
    op.drop_table("training_metrics")
    op.drop_index(op.f("ix_sample_annotations_sample_id"), table_name="sample_annotations")
    op.drop_index("ix_annotations_sample", table_name="sample_annotations")
    op.drop_table("sample_annotations")
    op.drop_index("ix_quality_version_code", table_name="quality_findings")
    op.drop_index(op.f("ix_quality_findings_version_id"), table_name="quality_findings")
    op.drop_table("quality_findings")
    op.drop_index(op.f("ix_lifecycle_artifacts_job_id"), table_name="lifecycle_artifacts")
    op.drop_table("lifecycle_artifacts")
    op.drop_index(op.f("ix_dataset_changes_version_id"), table_name="dataset_changes")
    op.drop_index("ix_dataset_changes_sample_created", table_name="dataset_changes")
    op.drop_table("dataset_changes")
    op.drop_index(op.f("ix_lifecycle_jobs_status"), table_name="lifecycle_jobs")
    op.drop_index("ix_lifecycle_jobs_queue", table_name="lifecycle_jobs")
    op.drop_index(op.f("ix_lifecycle_jobs_project_id"), table_name="lifecycle_jobs")
    op.drop_index(op.f("ix_lifecycle_jobs_owner_id"), table_name="lifecycle_jobs")
    op.drop_index(op.f("ix_lifecycle_jobs_kind"), table_name="lifecycle_jobs")
    op.drop_table("lifecycle_jobs")
    op.drop_index("ix_dataset_samples_version_split", table_name="dataset_samples")
    op.drop_index(op.f("ix_dataset_samples_version_id"), table_name="dataset_samples")
    op.drop_index("ix_dataset_samples_version_hash", table_name="dataset_samples")
    op.drop_index(op.f("ix_dataset_samples_sha256"), table_name="dataset_samples")
    op.drop_table("dataset_samples")
    op.drop_index("ix_dataset_versions_dataset_status", table_name="dataset_versions")
    op.drop_index(op.f("ix_dataset_versions_dataset_id"), table_name="dataset_versions")
    op.drop_table("dataset_versions")
    op.drop_index("ix_datasets_project_status", table_name="datasets")
    op.drop_index(op.f("ix_datasets_project_id"), table_name="datasets")
    op.drop_index(op.f("ix_datasets_owner_id"), table_name="datasets")
    op.drop_table("datasets")
    op.drop_index(op.f("ix_dataset_categories_code"), table_name="dataset_categories")
    op.drop_table("dataset_categories")
    # ### end Alembic commands ###
